# a={"a":1,"b":2}
# # a.pop("a")
# # print(a)
# # a.popitem()
# # print(a)
# # a.copy()
# # print(a)
# # a.clear()
# # print(a)
# # del(a["a"])
# # print(a)
# s=a.items()
# print(s)
# print(type(s))
# s=a.keys()
# print(s)
# print(type(s))
# s=a.values()
# print(s)
# print(type(s))
# # a.update({"c":"d"})
# # print(a)
# # a=(1,2)
# # v=0
# # was=dict.fromkeys(a,v)
# # # print(was)
# # a={"g":6,"b":9}
# # g=sorted(a.items())
# print(g)
a={}